CREATE TABLE PERSON_CONTACT ( 
	ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NAME CHAR(30) NOT NULL DEFAULT '' ,
	COMPANY CHAR(30) NOT NULL DEFAULT '' ,
	PROF_IMG CHAR(30) NOT NULL DEFAULT '' ,
	DOB CHAR(30) NOT NULL DEFAULT '' ,
	WRK_NUM CHAR(10) NOT NULL DEFAULT '' ,
	PER_NUM CHAR(10) NOT NULL DEFAULT '' ,
	EMAIL CHAR(30) NOT NULL DEFAULT '' ,
	ADDRESS CHAR(30) NOT NULL DEFAULT '' ,
	CITY CHAR(15) NOT NULL DEFAULT '' ,
	STATE CHAR(2) NOT NULL DEFAULT '' ,
	ZIPCODE CHAR(6) NOT NULL DEFAULT '' ,
	CCODE CHAR(2) NOT NULL DEFAULT '' 
	);
